name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Insurance Verification API Testing.json" -e "16858264-f84d5e3b-d9fc-4cad-9b35-1f579712f524" --integration-id "143892-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 057ffa72-9a51-4750-a526-12ad140cc7e1 --integration-id 143892
